version: '3.9'

services:

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - "8080:80"
      - "8083:443"
    networks:
      - app-network
    logging:
      driver: none

  node1:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=node1
    depends_on:
      - mongo
    networks:
      - app-network

  node2:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=node2
    depends_on:
      - mongo
    networks:
      - app-network
  
  node3:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=node3
    depends_on:
      - mongo
    networks:
      - app-network
  
  mongo:
    image: mongo:latest
    networks:
      - app-network
    ports:
      - '27017:27017'
    logging:
      driver: none
    
    

networks:
  app-network:
    driver: bridge
